project:
  type: website
  output-dir: docs

website:
  title: "RH Stadium Spectrum Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Overview
      - href: 1920_1930_mhz.qmd
        text: 1920–1930 MHz
      - href: 5p8ghz_links.qmd
        text: 5.8 GHz Links
      - href: longitudinal_psd.qmd
        text: Temporal PSD

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

  
resources:
  - content/rh_image.jpeg
  - content/rh_platform0.mp4